name: Dataset Validation CI

on:
  pull_request:
    paths:
      - 'rubbish_dataset.txt'  # Monitor changes to your dataset file

jobs:
  validate:
    runs-on: ubuntu-latest  # Use a clean Ubuntu environment for the build

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2  # Clone the repo to the CI environment

      - name: Check for emojis or special characters
        run: |
          # Regex to detect emojis or non-alphanumeric characters
          if grep -P -q '[\x{1F600}-\x{1F64F}\x{1F300}-\x{1F5FF}\x{1F680}-\x{1F6FF}\x{1F700}-\x{1F77F}\x{1F780}-\x{1F7FF}\x{1F800}-\x{1F8FF}\x{1F900}-\x{1F9FF}\x{1FA00}-\x{1FA6F}\x{1FA70}-\x{1FAFF}\x{2600}-\x{26FF}\x{2700}-\x{27BF}\x{2300}-\x{23FF}\x{2B50}\x{2764}\x{1F9D1}-\x{1F9FF}]' rubbish_dataset.txt; then
            echo "Error: Emojis or special characters found in the dataset." && exit 1
          fi
          echo "No emojis or special characters found."
